<a href="https://colab.research.google.com/github/swahar2/Python/blob/main/This_is_Jeopardy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This is Jeopardy!

#### Overview

This project is slightly different than others you have encountered thus far. Instead of a step-by-step tutorial, this project contains a series of open-ended requirements which describe the project you'll be building. There are many possible ways to correctly fulfill all of these requirements, and you should expect to use the internet, Codecademy, and/or other resources when you encounter a problem that you cannot easily solve.

#### Project Goals

You will work to write several functions that investigate a dataset of _Jeopardy!_ questions and answers. Filter the dataset for topics that you're interested in, compute the average difficulty of those questions, and train to become the next Jeopardy champion!

## Prerequisites

In order to complete this project, you should have completed the Pandas lessons in the <a href="https://www.codecademy.com/learn/paths/analyze-data-with-python">Analyze Data with Python Skill Path</a>. You can also find those lessons in the <a href="https://www.codecademy.com/learn/data-processing-pandas">Data Analysis with Pandas course</a> or the <a href="https://www.codecademy.com/learn/paths/data-science/">Data Scientist Career Path</a>.

Finally, the <a href="https://www.codecademy.com/learn/practical-data-cleaning">Practical Data Cleaning</a> course may also be helpful.

## Project Requirements

1. We've provided a csv file containing data about the game show _Jeopardy!_ in a file named `jeopardy.csv`. Load the data into a DataFrame and investigate its contents. Try to print out specific columns.

   Note that in order to make this project as "real-world" as possible, we haven't modified the data at all - we're giving it to you exactly how we found it. As a result, this data isn't as "clean" as the datasets you normally find on Codecademy. More specifically, there's something odd about the column names. After you figure out the problem with the column names, you may want to rename them to make your life easier for the rest of the project.
   
   In order to display the full contents of a column, we've added this line of code for you:
   
   ```py
   pd.set_option('display.max_colwidth', None)
   ```

In [2]:
from google.colab import files
uploaded = files.upload()

Saving jeopardy.csv to jeopardy.csv

In [24]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [25]:
jeopardy = pd.read_csv('jeopardy.csv')
jeopardy.head()

,Show Number,Air Date,Round,Category,Value,Question,Answer
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was under house arrest for espousing this man's theory",Copernicus
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,"No. 2: 1912 Olympian; football star at Carlisle Indian School; 6 MLB seasons with the Reds, Giants & Braves",Jim Thorpe
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,"The city of Yuma in this state has a record average of 4,055 hours of sunshine each year",Arizona
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", this company served its billionth burger",McDonald's
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Constitution of Mass., second President of the United States",John Adams

In [26]:
jeopardy.columns

Index(['Show Number', ' Air Date', ' Round', ' Category', ' Value',
       ' Question', ' Answer'],
      dtype='object')

In [27]:
jeopardy.columns = jeopardy.columns.str.strip()
jeopardy.columns

Index(['Show Number', 'Air Date', 'Round', 'Category', 'Value', 'Question',
       'Answer'],
      dtype='object')

2. Write a function that filters the dataset for questions that contains all of the words in a list of words. For example, when the list `["King", "England"]` was passed to our function, the function returned a DataFrame of 49 rows. Every row had the strings `"King"` and `"England"` somewhere in its `" Question"`.

   Test your function by printing out the column containing the question of each row of the dataset.

In [28]:
def list_of_words(data, words):
  filter = lambda x: all(word in x for word in words)
  return data[data['Question'].apply(filter)]

3. Test your original function with a few different sets of words to try to find some ways your function breaks. Edit your function so it is more robust.

   For example, think about capitalization. We probably want to find questions that contain the word `"King"` or `"king"`.
   
   You may also want to check to make sure you don't find rows that contain substrings of your given words. For example, our function found a question that didn't contain the word `"king"`, however it did contain the word `"viking"` &mdash; it found the `"king"` inside `"viking"`. Note that this also comes with some drawbacks &mdash; you would no longer find questions that contained words like `"England's"`.

In [29]:
df_funtion_result = list_of_words(jeopardy, ['King', 'England'])
print(df_funtion_result)

        Show Number    Air Date             Round  \
4953           3003  1997-09-24  Double Jeopardy!
14912          2832  1996-12-17         Jeopardy!
21511          4650  2004-11-19         Jeopardy!
23810          4862  2005-11-01         Jeopardy!
27555          1799  1992-05-28  Double Jeopardy!
33294          5589  2008-12-18         Jeopardy!
41148          5925  2010-05-21  Double Jeopardy!
41357          2751  1996-07-15         Jeopardy!
43122          3937  2001-10-16  Double Jeopardy!
47814          4365  2003-07-18  Double Jeopardy!
49994          5499  2008-07-03         Jeopardy!
51115          3574  2000-03-02         Jeopardy!
51565          4264  2003-02-27  Double Jeopardy!
56600          3533  2000-01-05  Double Jeopardy!
57516          4299  2003-04-17  Double Jeopardy!
58949          6250  2011-11-18  Double Jeopardy!
71808          5270  2007-07-06         Jeopardy!
74235          2757  1996-09-03         Jeopardy!
77195          3656  2000-06-26         Jeopardy!
79457          4230  2003-01-10  Double Jeopardy!
80113          5827  2010-01-05         Jeopardy!
84639          1558  1991-05-15         Jeopardy!
86412          1837  1992-09-08  Double Jeopardy!
89710          5390  2008-02-01  Double Jeopardy!
111926         1331  1990-05-21         Jeopardy!
118809         1905  1992-12-11         Jeopardy!
123299         4656  2004-11-29         Jeopardy!
123671         5718  2009-06-17         Jeopardy!
125822         4042  2002-03-12  Double Jeopardy!
127484         1325  1990-05-11  Double Jeopardy!
127758         6021  2010-11-15         Jeopardy!
129106         4906  2006-01-02  Double Jeopardy!
130208         5222  2007-05-01         Jeopardy!
137818         3368  1999-04-07         Jeopardy!
143434         1882  1992-11-10  Double Jeopardy!
150880         4790  2005-06-03  Double Jeopardy!
165110         4255  2003-02-14         Jeopardy!
165197         6272  2011-12-20  Double Jeopardy!
170007         5455  2008-05-02  Double Jeopardy!
174055         2143  1993-12-22  Double Jeopardy!
175259         3055  1997-12-05  Double Jeopardy!
183462         3099  1998-02-05   Final Jeopardy!
186239         5339  2007-11-22  Double Jeopardy!
187651         5264  2007-06-28         Jeopardy!
191579         5453  2008-04-30         Jeopardy!
192265         6292  2012-01-17  Double Jeopardy!
192966         6175  2011-06-17  Double Jeopardy!
194516         6114  2011-03-24  Double Jeopardy!
200369         2937  1997-05-13         Jeopardy!

                            Category     Value  \
4953                    "PH"UN WORDS      $200
14912                  WORLD HISTORY      $100
21511                     THE "O.C."     $1000
23810                  NAME THE YEAR      $400
27555               HISTORIC IN-LAWS      $600
33294            THE BAYEUX TAPESTRY      $600
41148                       TREATIES     $1600
41357                 HISTORIC NAMES      $400
43122                     OH, HENRY!      $400
47814                        POTIONS     $2000
49994                    REIGN DROPS     $1000
51115             ALL THINGS BRITISH      $200
51565             MUSIC APPRECIATION      $800
56600                 FRENCH HISTORY      $600
57516               THE "UN"CATEGORY     $2000
58949            ASSUME THE POSITION     $2000
71808        WHERE THERE'S A WILLIAM     $1000
74235                  WORLD HISTORY      $200
77195                        JUNE 26      $400
79457                     CONQUERORS      $800
80113                      "M" & "M"     $1000
84639              FILMS OF THE '90S      $200
86412                        ROYALTY      $400
89710                 "CAN"NED WORDS     $1600
111926                FILE UNDER "M"    $1,000
118809                KINGS & QUEENS      $300
123299                        CHAIRS      $400
123671          A YEAR ENDING IN '09     $1000
125822              PAINT IT "BLACK"    $5,000
127484               MEDIEVAL PEOPLE      $600
127758                   STATE FACTS      $600
129106            HISTORIC NICKNAMES     $2000
130208                       ROYALTY      $600
137818             PEOPLE IN HISTORY      $400
143434                           ART      $800
150880  20th CENTURY BRITISH HISTORY     $1200
165110                     HIGH COUP     $1000
165197           TOUCHED BY AN ANGEL     $2000
170007               THE SWEET 1600s     $1600
174055               HISTORIC PEOPLE      $200
175259                     THE 1930s      $400
183462                       ROYALTY  no value
186239              EUROPEAN HISTORY      $800
187651   CAPITALS OF THE WEST INDIES      $600
191579                       BATTLES      $800
192265    NORWAY'S CULTURE & HISTORY     $1600
192966                 HERO SANDWICH      $800
194516           THE YUCKS STOP HERE     $1600
200369               BRITISH HISTORY      $200

                                                                                                                                                                                                                                                                                                                                                        Question  \
4953                                                                                                                                                                                                                                                                    Both England's King George V & FDR put their stamp of approval on this "King of Hobbies"
14912                                                                                                                                                                                                                                                          This country's King Louis IV was nicknamed "Louis From Overseas" because he was raised in England
21511                                                                                                                                                                                                                                                                               this man and his son ruled England following the execution of King Charles I
23810                                                                                                                                                                                                                                                       William the Conqueror was crowned King of England in Westminster Abbey on Christmas Day in this year
27555                                                                                                                                                                                                                                                                         This member of the Medici family was the mother-in-law of England's King Charles I
33294               (Sarah of the Clue Crew delivers the clue from the Bayeux Cathedral in France.)  Despite taking an oath to assure another succession, Harold is crowned King of England; the tapestry indicated it was <a href="http://www.j-archive.com/media/2008-12-18_J_08.jpg" target="_blank">Stigant</a>, this archbishop, who performed the ceremony
41148                                                                                                                                                                                                                                  This French king recognized William of Orange as William II, King of England, under the terms of 1697's Treaty of Ryswick
41357                                                                                                                                                                                                                                                   England's King Henry VIII had 3 wives named Catherine:  Catherine Howard, Catherine of Aragon & this one
43122                                                                                                                                                                                                                                                                                                                     The father of England's King Edward VI
47814                                                                                                                                                                                                                                                                                                 This steak sauce was created for King George IV of England
49994                                                                                                                                                                                                                                                                     Elizabeth I's half-brother, he reigned before her as King of England from 1547 to 1553
51115                                                                                                                (<a href="http://www.j-archive.com/media/2000-03-02_J_22.jpg" target="_blank">Alex Trebek reads from England.</a>)  In 1214 barons fed up with King John met at the abbey whose ruins we see here; the result a year later was this charter
51565                                                                                                                                                                                                                                               He wrote several anthems, including "The King Shall Rejoice", for the coronation of England's King George II
56600                                                                                                                                                                                                                                                            This city known for its 24-hour auto race was the birthplace of England's King Henry II in 1133
57516                                                                                                                                                                                                                                                                                       Famous (& rather insulting) adjective for England's King Ethelred II
58949                                                                                                                                                                                                                                                                      He became King of England in 1399 after forcing his cousin Richard II from the throne
71808                                                                                                                                                                                                                                                                                    Number of the William who was England's "Sailor King" from 1830 to 1837
74235                                                                                                                                                                                                                                                                   Barons & churchmen drew up this 1215 document to reduce the power of England's King John
77195                                                                                                                                                                                                                                                        He became King of England on June 26, 1483; just over 2 years later he was killed at Bosworth Field
79457                                                                                                                                                                                                                                            On Christmas Day 1066, he was crowned King of England, 72 days after defeating Harold at the Battle of Hastings
80113                                                                                                                                                                                                                                                                                              England's King Charles II was known by this "jovial" nickname
84639                                                                                                                                                                                                                                                                          He went from second banana on "Roseanne" to top banana of England in "King Ralph"
86412                                                                                                                                                                                                                                                                       This country's King Olaf V was born in England & was the grandson of King Edward VII
89710                                                                                                                                                                                                                                                          This 11th Century King of England also ruled Denmark & Norway during the latter part of his reign
111926                                                                                                                                                                                                                                                 It begins "John, by the grace of God, King of England, Lord of Ireland, Duke of Normandy & Aquitaine...."
118809                                                                                                                                                                                                                                                                                          In French this King of England is called Guillaume le Conquerant
123299                                                                                                                                                                                                                                                                   If you want to be crowned King of England, this rock has to be in your coronation chair
123671                                                                                                                                                                                                                                                                                                                            King Henry VII of England dies
125822                                                                                                                                                                                                                                                                                            Famous nickname of the eldest son of England's King Edward III
127484                                                                                                                                                                                                                                                              Ethelred the Unready managed to lose most of England to King Sweyn Forkbeard of this country
127758                                                                                                                                                                                                                                                                                This state was named for the King of England who reigned from 1727 to 1760
129106                                                                                                                                                                                                                                                            King Edward I of England, who fought William Wallace, had this nickname relating to his height
130208                                                                                                                                                                                                                                                                                  This "Sun King" sniffed, "England is a little garden full of sour weeds"
137818                                                                                                                                                                                                                                                                                      The last King William to rule England had this number after his name
143434                                                                                                                                                                                                                                                              This Flemish artist painted a unique triple portrait of England's King Charles I around 1637
150880                                                                                                                                                                                                                                                                                     During Stanley Baldwin's term as P.M., this King of England abdicated
165110                                                                                                                                                                                                                                                      The 1st commoner to rule England, he became lord protector following the overthrow of King Charles I
165197                                                                                                                                                                                                                                                     The "Angel of Hadley" is said to have saved a New England town during the war with this Indian "King"
170007                                                                                                                                                                                                                                                              In the 1697 Treaty of Rijswijk, the French recognized this Dutch-born man as King of England
174055                                                                                                                                                                                                                                                                                          This conqueror was crowned King of England on Christmas Day 1066
175259                                                                                                                                                                                                                                                                                                        His short reign as King of England fell in in 1936

In [30]:
print(len(df_funtion_result))

49

In [31]:
df_funtion_result2 = list_of_words(jeopardy, ['King', 'england', 'viking'])
print(df_funtion_result2)

Empty DataFrame
Columns: [Show Number, Air Date, Round, Category, Value, Question, Answer]
Index: []

In [32]:
def list_of_words(data, words):
  filter = lambda x: all(word.lower() in x.lower().split() for word in words)
  return data[data['Question'].apply(filter)]

df_funtion_result3 = list_of_words(jeopardy, ['King', 'england'])
print(df_funtion_result3)

        Show Number    Air Date             Round               Category  \
6337           3517  1999-12-14  Double Jeopardy!                    Y1K
9191           3907  2001-09-04  Double Jeopardy!         WON THE BATTLE
13454          4726  2005-03-07         Jeopardy!  A NUMBER FROM 1 TO 10
14912          2832  1996-12-17         Jeopardy!          WORLD HISTORY
18076          3227  1998-09-22  Double Jeopardy!          WORLD HISTORY
...             ...         ...               ...                    ...
200369         2937  1997-05-13         Jeopardy!        BRITISH HISTORY
201168         3515  1999-12-10         Jeopardy!         BEFORE & AFTER
208742         4863  2005-11-02  Double Jeopardy!         BEFORE & AFTER
213870         5856  2010-02-15  Double Jeopardy!                 URANUS
216021         1881  1992-11-09  Double Jeopardy!         HISTORIC NAMES

         Value  \
6337      $800
9191      $800
13454    $1000
14912     $100
18076    $1000
...        ...
200369    $200
201168    $500
208742  $3,000
213870   $1600
216021   $1000

                                                                                                               Question  \
6337             In retaliation for Viking raids, this "Unready" king of England attacks Norse areas of the Isle of Man
9191                           This king of England beat the odds to trounce the French in the 1415 Battle of Agincourt
13454                                              It's the number that followed the last king of England named William
14912                 This country's King Louis IV was nicknamed "Louis From Overseas" because he was raised in England
18076                   In 1199 this crusader king of England was mortally wounded while besieging the castle of Chalus
...                                                                                                                 ...
200369  8th C. King Offa built a 170-mile north-south dike that still partly marks the border of England & this country
201168                                         Popular Saint-Exupery character waiting around to become king of England
208742                             Dutch-born king who ruled England jointly with Mary II & is a tasty New Zealand fish
213870                       In 1781 William Herschel discovered Uranus & initially named it after this king of England
216021                 His nickname was "Bertie", but he used this name & number when he became king of England in 1901

                            Answer
6337                      Ethelred
9191                       Henry V
13454                            4
14912                       France
18076      Richard the Lionhearted
...                            ...
200369                       Wales
201168  The Little Prince of Wales
208742    William of Orange roughy
213870                  George III
216021                  Edward VII

[74 rows x 7 columns]

4. We may want to eventually compute aggregate statistics, like `.mean()` on the `" Value"` column. But right now, the values in that column are strings. Convert the`" Value"` column to floats. If you'd like to, you can create a new column with float values.

   While most of the values in the `" Value"` column represent a dollar amount as a string, note that some do not &mdash; these values will need to be handled differently!

   Now that you can filter the dataset of question, use your new column that contains the float values of each question to find the "difficulty" of certain topics. For example, what is the average value of questions that contain the word `"King"`?
   
   Make sure to use the dataset that contains the float values as the dataset you use in your filtering function.

In [33]:
jeopardy["Value"].unique()

array(['$200', '$400', '$600', '$800', '$2,000', '$1000', '$1200',
       '$1600', '$2000', '$3,200', 'no value', '$5,000', '$100', '$300',
       '$500', '$1,000', '$1,500', '$1,200', '$4,800', '$1,800', '$1,100',
       '$2,200', '$3,400', '$3,000', '$4,000', '$1,600', '$6,800',
       '$1,900', '$3,100', '$700', '$1,400', '$2,800', '$8,000', '$6,000',
       '$2,400', '$12,000', '$3,800', '$2,500', '$6,200', '$10,000',
       '$7,000', '$1,492', '$7,400', '$1,300', '$7,200', '$2,600',
       '$3,300', '$5,400', '$4,500', '$2,100', '$900', '$3,600', '$2,127',
       '$367', '$4,400', '$3,500', '$2,900', '$3,900', '$4,100', '$4,600',
       '$10,800', '$2,300', '$5,600', '$1,111', '$8,200', '$5,800',
       '$750', '$7,500', '$1,700', '$9,000', '$6,100', '$1,020', '$4,700',
       '$2,021', '$5,200', '$3,389', '$4,200', '$5', '$2,001', '$1,263',
       '$4,637', '$3,201', '$6,600', '$3,700', '$2,990', '$5,500',
       '$14,000', '$2,700', '$6,400', '$350', '$8,600', '$6,300', '$250',
       '$3,989', '$8,917', '$9,500', '$1,246', '$6,435', '$8,800',
       '$2,222', '$2,746', '$10,400', '$7,600', '$6,700', '$5,100',
       '$13,200', '$4,300', '$1,407', '$12,400', '$5,401', '$7,800',
       '$1,183', '$1,203', '$13,000', '$11,600', '$14,200', '$1,809',
       '$8,400', '$8,700', '$11,000', '$5,201', '$1,801', '$3,499',
       '$5,700', '$601', '$4,008', '$50', '$2,344', '$2,811', '$18,000',
       '$1,777', '$3,599', '$9,800', '$796', '$3,150', '$20', '$1,810',
       '$22', '$9,200', '$1,512', '$8,500', '$585', '$1,534', '$13,800',
       '$5,001', '$4,238', '$16,400', '$1,347', '$2547', '$11,200'],
      dtype=object)

In [34]:
jeopardy['value_float'] = jeopardy['Value'].apply(lambda x: float(x[1:].replace(',','')) if x != 'no value' else 0.0)
jeopardy.head()

,Show Number,Air Date,Round,Category,Value,Question,Answer,value_float
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was under house arrest for espousing this man's theory",Copernicus,200.0
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,"No. 2: 1912 Olympian; football star at Carlisle Indian School; 6 MLB seasons with the Reds, Giants & Braves",Jim Thorpe,200.0
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,"The city of Yuma in this state has a record average of 4,055 hours of sunshine each year",Arizona,200.0
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", this company served its billionth burger",McDonald's,200.0
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Constitution of Mass., second President of the United States",John Adams,200.0

In [35]:
def check_question_difficuly_average(word):
  word = word.lower()
  return jeopardy[jeopardy['Question'].str.contains(word)]['value_float'].mean()

print(check_question_difficuly_average('king'))

772.688998469648

5. Write a function that returns the count of unique answers to all of the questions in a dataset. For example, after filtering the entire dataset to only questions containing the word `"King"`, we could then find all of the unique answers to those questions. The answer "Henry VIII" appeared 55 times and was the most common answer.

In [36]:
def unique_answers(word):
  word = word.lower()
  return jeopardy[jeopardy['Question'].str.contains(word)]['Answer'].value_counts()

print(unique_answers('king'))

Answer
Henry VIII       53
Richard III      31
Solomon          30
David            25
Louis XIV        24
                 ..
mockingbird       1
John Major        1
Son of Sam        1
adrift            1
telecommuting     1
Name: count, Length: 4452, dtype: int64

Investigate the ways in which questions change over time by filtering by the date. How many questions from the 90s use the word "Computer" compared to questions from the 2000s?

In [37]:
jeopardy['Year'] = pd.to_datetime(jeopardy['Air Date']).dt.year
jeopardy

,Show Number,Air Date,Round,Category,Value,Question,Answer,value_float,Year
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was under house arrest for espousing this man's theory",Copernicus,200.0,2004
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,"No. 2: 1912 Olympian; football star at Carlisle Indian School; 6 MLB seasons with the Reds, Giants & Braves",Jim Thorpe,200.0,2004
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,"The city of Yuma in this state has a record average of 4,055 hours of sunshine each year",Arizona,200.0,2004
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", this company served its billionth burger",McDonald's,200.0,2004
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Constitution of Mass., second President of the United States",John Adams,200.0,2004
...,...,...,...,...,...,...,...,...,...
216925,4999,2006-05-11,Double Jeopardy!,RIDDLE ME THIS,$2000,This Puccini opera turns on the solution to 3 riddles posed by the heroine,Turandot,2000.0,2006
216926,4999,2006-05-11,Double Jeopardy!,"""T"" BIRDS",$2000,"In North America this term is properly applied to only 4 species that are crested, including the tufted",a titmouse,2000.0,2006
216927,4999,2006-05-11,Double Jeopardy!,AUTHORS IN THEIR YOUTH,$2000,"In Penny Lane, where this ""Hellraiser"" grew up, the barber shaves another customer--then flays him alive!",Clive Barker,2000.0,2006
216928,4999,2006-05-11,Double Jeopardy!,QUOTATIONS,$2000,"From Ft. Sill, Okla. he made the plea, Arizona is my land, my home, my father's land, to which I now ask to... return""",Geronimo,2000.0,2006
216929,4999,2006-05-11,Final Jeopardy!,HISTORIC NAMES,no value,A silent movie title includes the last name of this 18th c. statesman & favorite of Catherine the Great,Grigori Alexandrovich Potemkin,0.0,2006

In [38]:
jeopardy['Year'].unique()

array([2004, 2010, 2000, 2006, 2009, 1996, 2007, 1997, 2002, 2003, 2001,
       1990, 1999, 2008, 2011, 2005, 1998, 2012, 1992, 1986, 1985, 1991,
       1993, 1994, 1988, 1987, 1995, 1984, 1989], dtype=int32)

In [39]:
jeopardy['Question'] = jeopardy['Question'].str.lower()

jeopardy_90s = jeopardy[jeopardy['Year'].between(1990, 1999)]['Question'].str.contains('computer').sum()
jeopardy_2000s = jeopardy[jeopardy['Year'].between(2000, 2010)]['Question'].str.contains('computer').sum()

print(f'Questions from the 90s use the word "Computer": {jeopardy_90s}')
print(f'Questions from the 2000s use the word "Computer": {jeopardy_2000s}')

Questions from the 90s use the word "Computer": 98
Questions from the 2000s use the word "Computer": 298

Is there a connection between the round and the category? Are you more likely to find certain categories, like "Literature" in Single Jeopardy or Double Jeopardy?

In [43]:
round_category = jeopardy.groupby(['Round'])['Category'].apply(list).to_dict()
round_category_df = pd.DataFrame(round_category.items(), columns=['Round', 'Category'])
print(round_category_df)

              Round  \
0  Double Jeopardy!
1   Final Jeopardy!
2         Jeopardy!
3        Tiebreaker

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Category
0                                                          [DR. SEUSS AT THE MULTIPLEX, PRESIDENTIAL STATES OF BIRTH, AIRLINE TRAVEL, THAT OLD-TIME RELIGION, MUSICAL TRAINS, "X"s & "O"s, PRESIDENTIAL STATES OF BIRTH, AIRLINE TRAVEL, THAT OLD-TIME RELIGION, MUSICAL TRAINS, "X"s & "O"s, DR. SEUSS AT THE MULTIPLEX, AIRLINE TRAVEL, THAT OLD-TIME RELIGION, MUSICAL TRAINS, "X"s & "O"s, DR. SEUSS AT THE MULTIPLEX, AIRLINE TRAVEL, THAT OLD-TIME RELIGION, MUSICAL TRAINS, "X"s & "O"s, DR. SEUSS AT THE MULTIPLEX, AIRLINE TRAVEL, THAT OLD-TIME RELIGION, MUSICAL TRAINS, "X"s & "O"s, SCIENCE CLASS, KIDS IN SPORTS, JUST THE FACTS, SEE & SAY, NEWS TO ME, IN THE DICTIONARY, SCIENCE CLASS, KIDS IN SPORTS, JUST THE FACTS, SEE & SAY, NEWS TO ME, IN THE DICTIONARY, SCIENCE CLASS, KIDS IN SPORTS, JUST THE FACTS, SEE & SAY, NEWS TO ME, IN THE DICTIONARY, SCIENCE CLASS, KIDS IN SPORTS, JUST THE FACTS, SEE & SAY, NEWS TO ME, IN THE DICTIONARY, SCIENCE CLASS, KIDS IN SPORTS, JUST THE FACTS, SEE & SAY, NEWS TO ME, IN THE DICTIONARY, PEOPLE IN HISTORY, CINEMATIC DICTIONARY, IT'S OURS!, BRITISH FASHION, ANDY WARHOL, THEATRE CROSSWORD CLUES "M", PEOPLE IN HISTORY, CINEMATIC DICTIONARY, IT'S OURS!, BRITISH FASHION, ANDY WARHOL, THEATRE CROSSWORD CLUES "M", PEOPLE IN HISTORY, CINEMATIC DICTIONARY, IT'S OURS!, BRITISH FASHION, ANDY WARHOL, THEATRE CROSSWORD CLUES "M", PEOPLE IN HISTORY, CINEMATIC DICTIONARY, IT'S OURS!, ANDY WARHOL, THEATRE CROSSWORD CLUES "M", PEOPLE IN HISTORY, CINEMATIC DICTIONARY, IT'S OURS!, ANDY WARHOL, THEATRE CROSSWORD CLUES "M", ALASKA, INTERNATIONAL SPORTSMEN, DRAMA QUEENS, ANGELS, IN EXILE, THE "I"s HAVE IT, ALASKA, INTERNATIONAL SPORTSMEN, DRAMA QUEENS, ANGELS, IN EXILE, THE "I"s HAVE IT, ALASKA, INTERNATIONAL SPORTSMEN, DRAMA QUEENS, ANGELS, ...]
1  [THE SOLAR SYSTEM, HISTORIC WOMEN, SPORTS LEGENDS, THE MAP OF EUROPE, FAMOUS SHIPS, EUROPEAN HISTORY, BRITISH NOVELS, FLAGS OF THE WORLD, THE BRITISH THEATRE, THE CONSTITUTION, GEOGRAPHIC PHRASES, AMERICAN HISTORY, RANKS & TITLES, CANDY, THE PRESIDENCY, THEATRE, FILM CLASSICS, NONFICTION AUTHORS, KNOWLEDGE BY THE NUMBERS, FAMOUS NAMES, CABLE TELEVISION, THE 50 STATES, ASIA, WORLD GEOGRAPHY, 20th CENTURY BOOKS, 19th CENTURY POLITICIANS, PRESIDENTIAL ELECTIONS, INFLUENTIAL 19th CENTURY THINKERS, HISTORIC PROPERTY TRANSACTIONS, MOUNTAINS, ASIA, EMPIRES, SPORTS & THE MOVIES, FICTION, VICE PRESIDENTS, THE WESTERN HEMISPHERE, FAMOUS VOYAGES, BEFORE THEY WERE SENATORS, CLASSIC MOVIE CHARACTERS, SHAKESPEARE, TELEVISION & HISTORY, LITERARY TITLES, ANIMALS, IN THE DICTIONARY, THE METROPOLITAN MUSEUM OF ART, WORD AND PHRASE ORIGINS, SPORTS NAME ORIGINS, GAMBLING, 20th CENTURY VICE PRESIDENTS, FAMOUS TEENAGERS, WORLD CAPITALS, FAMOUS NAMES, LITERATURE OF THE 1800s, CIVIL WAR PEOPLE, FAMOUS NAMES, SCIENTISTS, SCIENTISTS, U.S. POLITICS, ARLINGTON'S TOMB OF UNKNOWNS, BOOK TITLES, HISTORIC ENGLISHMEN, SHAKESPEAREAN TRAGEDY CHARACTERS, 20th CENTURY NOTABLES, WORLD LEADERS, COUNTRIES' HIGHEST PEAKS, ODD TITLES, PRISONS, RIVERS, COMPOSERS, 20th CENTURY U.S. PRESIDENTS, ALL GOD'S CREATURES, 1950s ACHIEVEMENTS, IN THE BOOKSTORE, SHAKESPEAREAN TITLE CHARACTERS, THE WORLD OF ART, FOOD ETYMOLOGY, WORLD LEADERS, BRAND NAMES, AUTHORS, THE 50 STATES, THE PRESIDENCY, WORLD CITIES, 19TH CENTURY FICTION, BIOLOGY, SISTER CITIES, 20th CENTURY NOVELS, AFRICAN AMERICANS, TV CHARACTERS, SAINTHOOD, AMERICAN LITERATURE, U.S. RIVERS, NAMES IN THE NEWS, EXPLORERS, TELEVISION HISTORY, FAMOUS PEOPLE, FIRST NAMES, THE PARTS OF SPEECH, THE FUNNIES, FAMOUS FELINES, WORD ORIGINS, ...]
2    [HISTORY, ESPN's TOP 10 ALL-TIME ATHLETES, EVERYBODY TALKS ABOUT IT..., THE COMPANY LINE, EPITAPHS & TRIBUTES, 3-LETTER WORDS, HISTORY, ESPN's TOP 10 ALL-TIME ATHLETES, EVERYBODY TALKS ABOUT IT..., THE COMPANY LINE, EPITAPHS & TRIBUTES, 3-LETTER WORDS, HISTORY, ESPN's TOP 10 ALL-TIME ATHLETES, EVERYBODY TALKS ABOUT IT..., THE COMPANY LINE, EPITAPHS & TRIBUTES, 3-LETTER WORDS, HISTORY, ESPN's TOP 10 ALL-TIME ATHLETES, EVERYBODY TALKS ABOUT IT..., THE COMPANY LINE, EPITAPHS & TRIBUTES, 3-LETTER WORDS, HISTORY, ESPN's TOP 10 ALL-TIME ATHLETES, THE COMPANY LINE, EPITAPHS & TRIBUTES, 3-LETTER WORDS, GEOGRAPHY "E", RADIO DISNEY, PARTS OF PEACH, BE FRUITFUL & MULTIPLY, LET'S BOUNCE, RHYMES WITH SMART, GEOGRAPHY "E", RADIO DISNEY, PARTS OF PEACH, BE FRUITFUL & MULTIPLY, LET'S BOUNCE, RHYMES WITH SMART, GEOGRAPHY "E", RADIO DISNEY, PARTS OF PEACH, BE FRUITFUL & MULTIPLY, LET'S BOUNCE, RHYMES WITH SMART, GEOGRAPHY "E", RADIO DISNEY, PARTS OF PEACH, BE FRUITFUL & MULTIPLY, LET'S BOUNCE, RHYMES WITH SMART, GEOGRAPHY "E", RADIO DISNEY, PARTS OF PEACH, BE FRUITFUL & MULTIPLY, LET'S BOUNCE, RHYMES WITH SMART, ROYAL FEMALE NICKNAMES, TV ACTORS & ROLES, TRAVEL & TOURISM, "I" LADS, FOREWORDS, BACKWORDS, ROYAL FEMALE NICKNAMES, TV ACTORS & ROLES, TRAVEL & TOURISM, "I" LADS, FOREWORDS, BACKWORDS, ROYAL FEMALE NICKNAMES, TV ACTORS & ROLES, TRAVEL & TOURISM, "I" LADS, FOREWORDS, BACKWORDS, ROYAL FEMALE NICKNAMES, TV ACTORS & ROLES, TRAVEL & TOURISM, "I" LADS, FOREWORDS, BACKWORDS, ROYAL FEMALE NICKNAMES, TV ACTORS & ROLES, TRAVEL & TOURISM, "I" LADS, BACKWORDS, GENERAL SCIENCE, GETTING POSSESSIVE, FLAGS OF THE WORLD, ARCHITECTS, 1994 FILMS, THE EYES HAVE IT, GENERAL SCIENCE, GETTING POSSESSIVE, FLAGS OF THE WORLD, ARCHITECTS, 1994 FILMS, THE EYES HAVE IT, ...]
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [CHILD'S PLAY, THE AMERICAN REVOLUTION, LITERARY CHARACTERS]

In [48]:
Double_jeopardy_categories = set(round_category_df.loc[0, 'Category'])
Final_jeopardy_categories = set(round_category_df.loc[1, 'Category'])
Jeopardy_categories = set(round_category_df.loc[2, 'Category'])
Tiebreaker_categories = set(round_category_df.loc[3, 'Category'])

Items_unique_to_Double_jeopardy = Double_jeopardy_categories - Final_jeopardy_categories - Jeopardy_categories - Tiebreaker_categories
Items_unique_Final_jeopardy = Final_jeopardy_categories - Double_jeopardy_categories - Jeopardy_categories - Tiebreaker_categories
Items_unique_Jeopardy = Jeopardy_categories - Double_jeopardy_categories - Final_jeopardy_categories - Tiebreaker_categories
Items_unique_Tiebreaker = Tiebreaker_categories - Double_jeopardy_categories - Final_jeopardy_categories - Jeopardy_categories

print(f'Categories unique to Double Jeopardy: {Items_unique_to_Double_jeopardy}')
print(f'Categories unique to Final Jeopardy: {Items_unique_Final_jeopardy}')
print(f'Categories unique to Jeopardy: {Items_unique_Jeopardy}')
print(f'Categories unique to Tiebraker: {Items_unique_Tiebreaker}')

Categories unique to Double Jeopardy: {"WHAT'S OPERA, DOC?", 'ELECTION 2000', 'THE SMITHSONIAN JAZZ BAND', 'A LONG, LONG TIME AGO', 'SPELL-BOUND FOR BROADWAY', 'FAMOUS NAVAL CONFLICTS', 'COUNTRIES THAT END IN "O"', 'THEATRICAL QUOTES', 'MEASURE IT', 'TECUMSEH', "COTE D'IVOIRE", 'CRITTER LIT', 'SHALL WE PLAY A GAME?', 'BASEBALL MOVIES', 'MEMORABLE ROLES', 'WILL SHAKESPEARE, SERIAL KILLER', 'STOCK HOME', 'BORN THE SAME DAY', 'IN CHINA', 'REMBRANDT', 'THE AGE OF CHIVALRY', 'RAIN', "IF I'M ELECTED...", "'60s LYRICS", 'A SNAKEY CATEGORY', 'COLORFUL SCIENCE', "SHAKESPEARE'S B-STORIES", 'SOUP TALK', "NIXON'S CABINET", "AUTHORS' MAIDEN NAMES", 'FRENCH PHRASES', 'MOVIES ON THE MAP', 'OLD CITIES', 'HISTORICAL QUOTES', 'BOOKS ABOUT TV SHOWS', 'SHAKESPEARE ON LOVE', '17th CENTURY DRAMA', 'FAMOUS JESSICAS', '"SUM" IT UP', 'JOHN WAYNE FILMS', 'ANCIENT RELIGION', 'TELLING TALES OUT OF SCHOOL', 'DETENTE-TION', 'GHANA IN 60 SECONDS', 'THE GATHERING OF NATIONS', 'SINGULAR NAMES', 'KISMET', '"CAR" TALK', 'SONGFUL WOMEN', 'SMALLER THAN ALBUQUERQUE', 'CANADIAN ACTORS', 'AUTHORS IN THEIR YOUTH', "SHAKESPEARE'S COMIC CAST", 'SHOW ME THE MONET', 'SHAKESPEARE SLAYS ME', 'ASHES TO ASHES', 'STAR WARS FOREVER', "'90s NEWS", 'NICKEL & DIMED', 'TALKING REAL ESTATE', 'GA$', 'COMPOUNDS', 'GOING COUNTRY', "HEY, HEY WE'RE THE MAORIS!", 'TRANSPORTATION IN SONG', 'PROSE', 'HAVE AN AMSTERDAM GOOD TIME', 'MTM', 'FOR "RENT"', 'HEAVY METAL BANDS', 'STORES', '"OPE" SPRINGS ETERNAL', 'BUILDING BRIDGES', 'THE ART OF THE STEAL', 'RUDOLPHS & RUDOLFS', 'TV BEFORE & AFTER', 'IMAX FILMS', 'EAT, EAT!', 'AMERICAN ART & ARTISTS', 'I LOVE A MYSTERY', 'ANCIENT COUNTRIES', 'BIRD', "WHATCHA EATIN'?", 'GIMME MY HUNCHBACK', 'GIVE IT A "PUSH"', 'THE 9th CENTURY', 'P.C.', 'SOUNDING OFF', 'ROYAL LANDMARKS', "WHEE!  IT'S 1893!", 'WHAT HAPPENED TO THE "MOTHER"s?', 'PLACES TO PAY IN PESOS', 'HOUSE OF METAPHORS', 'SAINT PETERSBURG', 'A STUDY IN SCARLETT JOHANSSON', '"SOLE" TRAIN', 'JAI ALAI', 'MANHATTAN NEIGHBORHOODS', 'VALUES', 'THIS MUST BE POLAND', 'BANNED!', 'A TRIP TO LITERARY BRITAIN', 'DO YOU LIKE RUSSIAN HISTORY?', 'PHYSICS, BRAIN SURGERY & ROCKET SCIENCE', 'THE BEAR FACTS', '"UO" ME!', 'PHONY."COM"s', 'IT HAPPENED ON APRIL 2', '21st CENTURY MOVIE ROLES', 'THE 2009 TONY AWARDS', 'ENGLISH ROYAL HENRYS', 'COMPLETES THE POETRY LINE', 'BARD BITS', 'DEATH IN POP', '"I" REMEMBER', 'BUFF ACTORS', 'ORCHESTRA CONDUCTORS', 'ROUND IT OFF', 'COLORFUL AMERICA', 'EDIBLE NAMES', 'SPICE', 'JACKS IN THE BOX', 'HELEN KELLER', 'THE GENGHIS KHAN FILM FESTIVAL', 'ON YOUR TOES', '"I" CATCHING', '"GUN" SMOKE', '1850s AMERICA', 'TRIBUTE ALBUMS', 'ROCK-Y', '1980s FICTION', 'MESSIAH', "CLASSIC CINEMA OF THE '40s", '"END" AT THE BEGINNING', 'BASEBALL LIT', 'ROUTE 66 REVISITED', 'NAMES IN MEDICINE', 'ENTERTAIN ME!', 'FUN WITH PROBABILITY', 'FLY FISHING', 'CONSONANT-LESS COUNTRIES', 'SPORTS CAST', 'FOLKIES', 'CLASSIC SCI-FI & HORROR FILMS', '16th CENTURY AMERICA', 'FAMOUS MOUSTACHES', 'GEEK LETTER SOCIETIES', 'LANGUAGE OF ORIGIN', '1965', 'THAT SOUNDS "GREAT"', "DRIVER'S ED.", 'CHARLES V', 'THE FORBES 2009 BILLIONAIRES LIST', 'I, KANT', 'HYPHENATED TERMS', 'MARTIN LUTHER KING', 'NTERNATIONAL SPORTS TROPHIES', 'PROMINENT 20th CENTURY WOMEN', '"BERT"DAYS', 'WINE, WHITE WINE', 'EDISON & THE PHONOGRAPH', 'WILLA CATHER', 'PUBLISH OR PERISH', 'SIGNATURE SONGS', 'AN ARM', 'THE ITALIAN RENAISSANCE', '"OX" MARKS THE SPOT', 'WORLD OF KNOWLEDGE', 'LODGING', 'BILLIARDS', 'TALK TV', "WRITERS' PRIVATE LIVES", 'REMEMBER MY NAME', 'MEET T.S. ELIOT', '"SPIN" CITY', 'PICK "NIC"', 'LESSER-KNOWN ART & ARTISTS', 'THE GIFT OF "GAB"', '"UMP" IT UP', 'SUPERLATIVES', 'I BIT OFF MORE THAN I COULD CHEW', 'THAT WAS ENTERTAINMENT!', '"MISSION" POSSIBLE', 'THE WORLD COURT', 'HAUNTED HOUSEKEEPING', 'SCIENCE POTPOURRI', 'THAT\'LL BE THE "DAY"', 'CATCH THE "FLU"', "BOB'S YOUR POET", '"LO" MEN', "WE'RE WORLD CHAMPS", '1831', 'HAPPY TALK', 'DID YOU NOTICE?', 'SHOW BIZ ROOMIES', 'TIM CONWAY FILMS', 'AT THE BALLPARK', "LET'S GO TO HARVARD", "PLUTARCH'S LIVES", 'AUDREY HEPBURN', 'GIVE ME AN "E"', '...& THE HORSE YOU RODE IN ON!', 'ABBREVIATED PROVERBS', 'OOO, SORRY', 'CHILLING TALES', 'GEOGRAPHIC MEANINGS', '"POO"-POURRI', 'RHETORICALLY SPEAKING', 'BLUE BOOKS', 'PENGUINS', 'TOURIST TRAPS', 'HI "YO"', '"GENERAL" ASSEMBLY', 'AMERICAN FIRSTS', 'I THINK I LOVE HUGH', 'LOTS OF SPACE', "I'M FROM MISSOURI -- SHOW ME!", 'AMERICAN DIPLOMATS', '"C" IS FOR COOKING', "CHILDREN'S BOOK TITLES", '"IC" !!!', 'OF THE FLIES', 'ART "C" CROSSWORD CLUES', 'HOAXES & FRAUDS', 'SUPER BOWL BETS', '19TH CENTURY SCIENCE', 'SOUTH AMERICAN HISTORY', 'A BYZANTINE CATEGORY', 'ENTERTAINMENT NEWS', 'ON COMMISSIONS', 'HEY MR. WILSON!', 'QUESTION: MARKS', 'YOU KNOW MORE THAN YOU THINK', 'LEGEND SAYS...', 'YOU HAD TO EXPECT OPERA', 'PORTRAIT OF THE ARTIST', 'CHARACTER ASSASSINATION', 'MOON "R"s', 'FELIX, NOTHING MORE THAN FELIX', 'EVERYBODY TALKS ABOUT IT....', 'TV OPENING CREDITS', 'BACK TO LITERARY BRITAIN', 'BRINGING HOME KEVIN BACON', 'HALLOWEEN-POURRI', 'WORLD WAR II IN EUROPE', 'NONFICTION BEST SELLER OF THE YEAR', 'MORE REDUNDANCY & REPETITION', 'NICKNAMES GIVEN BY PRESIDENT BUSH', 'TV SHOWS BY CAST', 'YOU GLOW!', '"GOOD", "BAD" & "UGLY" MOVIES', 'A DAMSEL IN THIS DRESS', "WHERE THERE'S A WILL", '"RIGHT" OR "LEFT"', 'POLITICALLY CORRECT MUSICALS?', 'L.A. AREA MUSEUMS', 'BOXER', 'JOHNNY GILBERT RAPS & ROCKS ON', 'FILL IN THE BIBLICAL BLANK', "THAT'S OUR LEADER!", '"O", WHAT A PLACE!', 'VEGETABLE, ANIMAL OR MINERAL', 'VATICAN CITY', 'PHILADELPHIANS', 'BEASTLY HOMONYMS', 'AT THE BEGIN"ING"', 'ROGER!', 'MARK TWAIN: BOOK LOVER', 'POETIC JUSTICE', 'MADISON', 'KILL BILL: VOL. 2', 'THE MAJORS', 'THE HISTORY OF LIBYA', 'BIG CITY', 'MUSIC/TELEVISION', "IT'S A BIT CHILE TODAY", 'TO TELL THE TRUCE', 'LOS ANGELES', 'SPORTS ABBREV.', 'A SUCCESS WITH BRUSH', 'JAPANESE CUISINE', 'CANADIAN CUISINE, EH?', 'TAKE YOUR MEDICINE', 'THEY PLAYED JESSE JAMES', 'THE NEW YORK TIMES THEATER REVIEWS', 'LINCOLN BLOGS', 'SPELLING IT OUT IN ROMAN NUMERALS', "YOU'RE GOING TO WIN A PULITZER!", 'THE BEER GARDEN', 'THEY GOT STRUCK', 'DURING THE PIERCE ADMINISTRATION', '"GON" TOMORROW', 'ROMAN NUMERAL WORDS', 'CLOTHES MAKE THE PERSON', 'CURSING IN THE BIBLE', 'JOHN DONNE', "SHAKESPEARE'S EXIT LINES", 'SPIKE LEE', 'GETTING A"HEAD"', 'PLAYING POLITICS', 'UNIQUELY AMERICAN LITERATURE', 'PAINTING OF THE CENTURY', "FUNNY FOR NOTHIN'", 'NATURE WALK', 'CHARACTER IN JAMES FENIMORE COOPER', 'MR. OR MS. BROWN', '"P"SCIENCE & MEDICINE', 'THE REAL ADAMS FAMILY', 'THURBER', 'GIRL GROUPS', 'WHAT A DELICIOUS DISH', "THAT'S GONNA COST YOU", 'LET\'S GO FOR A "SPIN"', "THE SERPENT'S EGG", 'THEY MADE THE TOP 40', "PERKIN' UP", 'SEE HOW THEY RUN', 'MAN UP', 'THE "X" GAMES', 'A "BACH" OF CLUES', 'YOU WILL BE ASSIMILATED', 'BEFORE & AFTER MOVIE TITLES', 'POW-ER', 'LOVE POETRY WITH JOHNNY GILBERT', 'LABRADOR', '"POP" GOES THE CATEGORY', 'NOVEL ENDINGS', 'MINORITIES', 'WORDS FOR WORDS', "HOCKEY TEAMS' HOMES", 'VERY SPECIFIC FORTUNE COOKIES', '"YOUNG"', 'GET MOVING', 'XMAS NEWS & NOTES', 'LEGENDS OF SPORTS', 'RECENT OBITS', 'HISTORIC BIRTH ANNOUNCEMENTS', '"BUR" BANK', '20th CENTURY ARCHITECTURE', '"Q" FOOD & DRINK', "IT'S ONLY MONEY", 'MAA (military acronyms & abbreviations)', 'STAR WARS CHARACTERS', 'THE PULITZER PRIZE FOR FICTION', 'CHRISTIAN SLATER', 'ISAAC HAYES', '1930s TV', "WORLD LEADER DRIVER'S LICENSES?", '5 CONSONANTS IN A ROW', 'POP GOES THE EASEL', 'MY ACTING & POLITICAL RESUME', '2-WORD COUNTRIES', 'SEMITIC LANGUAGES', 'CAPITAL TOWNS', 'THE VIETNAM ERA', 'FAMILY FEUD', 'CRIMEA', 'A "P.C." CATEGORY', "NO, I DON'T NEED A DOCTOR", 'LOUD CLASSICAL MUSIC', 'HAPPY BIRTHDAY', 'THE LIBERTY BELL RANG...', 'MUSIC OLDER THAN YOU', '"HALF"', 'CLASSICAL SOUND EFFECTS', '"FINAL" JEOPARDY!', "OBJETS D'ART", 'FIJI', 'PHILOSOPHIC IDEAS', 'PUNS', 'FICTIONAL SISTERS', 'NOVEL BALLETS', 'WELL SAID', 'QUAD FOOD', '“SOUTH”', 'LEGAL BEFORE & AFTER', 'FORWARDS & BACK WORDS', '"LIKE"', 'DAYTIME TV', 'DEEP IN THE HEART OF TEXAS', 'THE FABULOUS FIFTIES', 'MICHELANGELO', 'SORORITY WOMEN', 'AFFAIRS OF STATE', '"KEY"', '"EAT" IT', 'EINSTEIN & FRIENDS', 'THE DUTCH ROYAL FAMILY', 'THROUGH THE 1800s WITH SARAH POLK', 'IT\'LL END IN "TEER"s', 'THE TWELVE', 'NAMED FOR PEOPLE', 'FUELS', 'THE GREAT "BEYOND"', 'SONGS ABOUT THE MOVIES', '1950', 'MOVIE NAMES', 'THE ORIGINAL BROADWAY CAST', 'IT HAPPENED ON DECEMBER 1', "ROYAL NAME'S THE SAME", 'HISPANIC AMERICA', 'LITERARY E-MAIL ADDRESSES', 'ISLAM', 'NOW IN STORE', 'MY TV TOWN', 'SOUNDS LIKE SPORTS EQUIPMENT', 'AMERICAN RIVERS', 'SWEET SIXTEEN', 'DISCOVERY CHANNEL UNSOLVED HISTORY', '"BAN"', 'SPORTS 2006', 'MEDITERRANEAN HISTORY', 'A JOURNEY THROUGH ISRAEL', 'THE OCCULT', 'SAN DIEGO', 'THURSDAY NIGHT TV', '"MY" BABY', 'OOH, A WISE GUY', 'COURT MONARCHS', 'START YOUR ENGINES', 'FAR"M"S', 'BACKING BANDS', 'PLAYS WITHIN PLAYS', 'HELLO AGAIN', 'HALLOWEEN CANDY', 'BILL MURRAY FILM QUOTES', 'HERE, KING!', 'THE BIG BANG', 'SOPRANOS', 'SOMEDAY THE SAINTS', 'FOLLOW THE LEADER TO THE CAPITAL', 'RING ANNOUNCER', 'GEOGRAPHICAL EXTREMES', 'ANIMA"L"S', 'THE BAR EXAM', 'CHANGES', 'HOUSEHOLD WORDS', 'OCTOBER 1', 'ANAGRAMMED THEORETICAL PHYSICISTS', 'YOU ARE SO FOXY!', 'A LITTLE OF EVERYTHING', 'RUSSIAN RECIPES', 'HUMORISTS', 'MORE THAN 13-LETTER WORDS', 'ZOOS', 'SINGLE-LETTER STOCKS', 'NORTH, CENTRAL & SOUTH AMERICAN LEADERS', '"PARA"GRAPHS', '"SOUTHERN" COMFORT', 'DEMONS', 'CAPTAIN KANGAROO', 'HISTORIC EUROPEAN LEADERS', 'NATIONAL HISTORIC LANDMARKS', '"B" SURE', 'SHAKESPEARE PLAYS BY CHARACTER', 'LESSER-KNOWN MOVIES', 'INTERNATIONAL "K"S', 'HOME, SWEET HOME', "'TIL DEATH", 'KING OF THE IMPOSSIBLE', 'CELL BLOCK CINEMA', 'TANK ARRAY', 'LIFE AFTER DEATH', 'COMMITTEES', 'STARDUST', "HEY HEY WE'RE THE MOUNTIES!", 'COLIN POWELL', 'THE JOY OF 6-LETTER WORDS', 'PLAY FASTER!', 'THE L"ONE"LIEST NUMBER', 'TURKEY LEFTOVERS', 'ODD SPELLING', 'HELLO, JASON!', 'MODERN AFRICAN WOMEN', 'FILM RENOIR', 'WHERE IT HAPPENED', 'ATE', 'MILLION', 'OCEANS', '"SEX" SELLS', 'IT ACTUALLY HAS A NAME', '"IBLE"S & BITS', 'IN THE GOOD OLD SUMER TIME', 'BUSINESS BENCHMARKS', 'BLOODY BUSINESS', 'SEEING EYE DOGS', 'BROWNSVILLE, TEXAS', 'LA ISLA BONITA', 'COMMANDERS AT WAR', 'DIPLOMACY', 'RENAISSANCE PAINTERS', 'ACROPOLIS NOW', 'LADIES IN SPACE', 'MELON-CHOLY', 'OBSCURE NOBEL PRIZE-WINNING AUTHORS', "'60s TV", 'JUDGE HATCHETT', 'RIDDLE ME THIS', 'LATINOS IN HOLLYWOOD', 'EXCLAMATION POINTS', 'NAMES IN SONG TITLES', 'FLOWERY PROSE', 'SOUTHERN CALIFORNIA ARCHITECTURE', 'OXFORD CHITCHAT', 'REQUESTS', 'TALK SHOW HOSTS', 'I WENT TO UCLA', 'VENEZUELAN HISTORY', 'WHAT KIND OF SHAPE ARE YOU IN?', 'NOTHING', 'IN CRISIS MODE', 'THE END OF THE LINE', 'SHAKESPEAREAN QUOTES', 'PRESIDENTIAL AILMENTS', "SHAKESPEARE'S SMALL PARTS", 'WORDS IN SHAKESPEARE', 'KEEPIN\' IT "REAL"', 'OTHER GRAND CANYONS', 'HIS PRO TEAM RIGHT BEFORE...', 'COLORFUL LIT', '1886', 'THE ART OF PEACE', '19TH CENTURY POLITICIANS', 'SATURDAY NIGHT LIVE RECURRING ROLES', 'POP & ROCK', 'ART EXHIBITS', "IT'S POISONOUS", '& SO I FACE THE FINAL CURTAIN', "OPRAH'S FAVORITE BOOKS", "BIRTHIN' BABIES", 'ERAS & AGES', 'THE HOOSIER STATE', 'BIBLE QUOTES', '2006 SPORTS LAUGHS', "TOLSTOY'S WAR AND PEACE", '"AR" WORDS', 'IN A STORM MOVIE', 'MIDWAY ISLAND', 'BEHIND THE MIKE', 'COMPLETES THE STAR TREK EPISODE TITLE', 'I "PASS"ED!', 'A SALUTE TO SALLY FIELD', 'JAPAN-U.S. RELATIONS', '1950s MOVIES', 'CRESCENT CITY ROLES', "JACK NICHOLSON'S OSCAR-NOMINATED ROLES", '"CAT"s & "DOG"s', 'THEY WERE STONED', 'ONE-WOMAN SHOWS', 'THE 18th CENTURY WORLD', 'THEATRE IN THE NEW YORK TIMES', 'FICTIONAL MOVIE BANDS', 'TORAH!  TORAH!  TORAH!', 'UNIVERSITY OF CHICAGO ALUMNI', 'ENDS WITH "ICE"', '"FI"', 'TALES OF E.T.A. HOFFMANN', "THAT'S POETRY TO MY EAR", 'YOU BETTER KNOW SOME SCIENCE', '"S" WONDERFUL', 'GOLDEN RETRIEVERS', "IT'S NOT EASY BEING TWEEN", 'COMEDY FILMS', 'THEY USED TO BE TEENAGERS', 'AROUND THE WORLD, J. PETERMAN STYLE', 'TOGO A GO-GO', 'FILL IN THE DICKENS TITLE', 'LOMBARDY', 'BREAKING THE ICE WITH ICEBREAKERS', 'ADVENTUROUS WOMEN', 'HAIR & MAKE-UP', '"UGH"!', 'HENCE THE TITLE', 'INFESTED WITH INSECTS', 'MOTHER JONES SAID', 'HAPPY BIRTHDAY, THE NEW YORK TIMES', 'HIT ME', 'THIRD PARTY CANDIDATES', "'50s FASHION", '2 ACTORS, SAME ROLE', '"T"EOGRAPHY', "THE WOMEN'S HALL OF FAME", "FOODS OF THE '40s", 'SCRAMBLED MAMMALS', 'THE YEAR IN SPORTS', 'BEER-VERTISING', '3 DAYS OF THE CONDOR', 'THE AGE OF RAISIN', 'ALL ABOARD FOR ALBANIA', "THINGS YOU SHOULDN'T PUT IN YOUR MOUTH", 'MARRY MARY', 'LITERARY ADJECTIVES', 'EXTRAS', 'THIS MEANS TROUBLE', 'MERRY OLD SOUL', 'OIL!', 'A-B-C', 'READ THE BOOK', 'PAINTINGS IN THE PRADO', 'CARIBBEAN PORTS OF CALL', "MOM'S THE WORD", '@$&!', '"V" HAVE MAPS', '"DOUBLE" JEOPARDY', 'WHAT DO U STAND FOR?', 'CHESTER A. ARTHUR', 'MORGAN FREEMAN FILM ROLES', 'PRINCESS', 'THE LANGUAGE OF LOVE', 'TREES & SHRUBS', '18th CENTURY ART', '"ME" IN THE MIDDLE', 'A NOVEL SUM-UP', 'JEOPA-CONGLOMAREX, INC.', 'OPERA, LIKE IT OR NOT', 'GETTING KNOTTY', 'JUPITER', '1989 BOOKS', 'SMALL MAMMALS', 'LAND OF THE DICTATOR', 'AUTO RACING 101', 'HEAD OF THE CLASSICAL MUSIC', 'MAD DOGS', "IT'S A COUP D'ETAT", 'WINTER SPORTS', '19TH CENTURY AUTHORS', 'ANCIENT GREEK DRAMA', "HEROD'S LOST TOMB", 'THE BICYCLE', 'TV TIDBITS', 'ALL I WANT FOR ISTHMUS', 'ARISTOTLE SAYS...', '"D"SERT', 'CLASSICAL COMPOSITIONS', 'MR. MOVIEFONE', 'CAPITOL RECORDS', 'ODE TO A SITCOM', "CHILDREN'S  LITERATURE", '"X"s & "O"s', 'U.S. GOVERNORS', 'KING OF QUEEN', 'TEENS UNDER THE MICROSCOPE', "WE'RE MALAYSIA-BOUND", "THAT'S MY KID!", 'ROBERT FROST SAYS...', '"ARG"!!!', 'AMERICAN POLITICAL IDOL', '"W"RITERS', 'THE MAUREEN CORPS', 'ENDS IN "GHT"', 'DON\'T BE AN "ASS"', 'STARS OF THE SILENT SCREEN', 'WHAT DID JESUS DO?', 'TOE-KNEE', 'A CD CATEGORY', 'SYMPHONY FOR THE DEVIL', 'TAXI!', 'TENNESSEE, ANYONE?', 'SOUNDS LIKE A SNACK CHIP', 'HUSKY', 'URBAN MOVIES', 'EDIBLE RESPONSES', 'THE ROTARY CLUB', 'THE TRUTH', 'ROLE IN COMMON', 'OPERAS TEENS LOVE', 'WHERE FOR ART', 'FANTASTIC MR. FOX', 'QUAY TO THE CITY', 'FAR AND AWAY', 'BELOVED BOLIVIA', 'WOOD HOUSE', 'CANADIAN MUSICIANS', 'NAME THAT POEM', 'JEAN-WHAT?', 'SIMON BOLIVAR', 'THE CALIFORNIA HIGHWAY PATROL', 'EVERYDAY SYMBOLS', 'TELLING TIME', 'YOUR LIFE ON THE BIG SCREEN', 'THUNDER & LIGHTNING', 'OLD NEWSPAPERS', 'NAME THEIR CENTURY', 'GILBERT & SULLIVAN', "BOOKS OF THE '80S", 'HOOVER DAM', 'FILM SCHOOL', 'THE "ACC"', 'DAN IN REAL LIFE', 'EXPLORERS OF THE NEW WORLD', 'THIS MOVIE IS "DEAD"', 'THESPIAN-"O"', "MUSTN'T SEE TV", 'HELLO, ETHAN', 'DAN', 'FERDINAND & ISABELLA', 'THE MAYFLOWER', 'OBSERVATORIES', 'TOUR DE FRANCE', 'THE USUAL GANG OF IDIOTS', 'SCI.', 'REMAINS TO BE SEEN', 'ANAGRAMMED RESPONSES', 'EYE ON THE UNIVERSE', 'LONG RUNS ON BROADWAY', "IT'S A FACT", '19th CENTURY AMERICAN LIT', 'PUTTING CELEBRITIES ON THE MAP', 'HISSSTORY', 'THE 104TH CONGRESS', '"HY" SCIENCE', '"BAD" MOVIES', 'GERMAN CITIES', 'DARWIN', 'WISDOM OF THE AGES', 'MRS. SMITH GOES TO WASHINGTON', 'HEAVY METALLURGY', 'SKINS', '"ACT" UP', 'LIVING IN "SIN"', 'FOREIGN LITERATURE', 'THIS IS A JOB FOR A HERO', 'BYPASS', 'BUT WHAT AM I?', 'LESSER-KNOWN POEMS', 'WE HAVE MET THE ANIME', 'TEENS OF THE PAST', 'INITIALED AUTHORS', 'URANUS', "THAT'S SO CONVENTIONAL!", 'GUEST EDITORS', 'LETTER HISTORIES', 'HAPPY CAMPERS', 'LOOK OUT "BELL"OW', 'EDWARDS', "WRITER'S HOMES", 'IT HAS TO END WITH "U"', 'MY SCENTIMENTS EXACTLY!', 'JOHN/PAUL', 'SAVING THE BEST FOR LAST', 'SCIENCE "T"ALK', 'Mcs & Macs', '500 YEARS AGO', '10-LETTER COUNTRIES', 'ARCTIC ANIMALS', 'LITERARY LINEUPS', 'COMPANIES NAMED AFTER PEOPLE', 'MALTA BOUND', 'ORDINAL PHRASES', 'GOING DOWN IN HISTORY', 'GREEK LIFE', "THAT'S GOTTA HURT!", '-ISH', 'I DID IT NORWAY', 'THE PHANTOM MENACE', 'WEAR IT WELL', 'OH, BEE GEE', 'CLASSIC TV DRAMA EPISODES', 'CHEMICAL STATES', 'MICHELLE PFEIFFER PFILMS', "'70s LIT", 'DICKENS CHARACTERS', 'POLITICAL TALK', 'TREKS', 'GO!', 'PLAYING THE BUFFOON', 'IMAGINARY LAW FIRMS', 'DANISH', 'MINDBENDING MISCELLANY', 'A.A.', 'DWIGHT D. EISENHOWER', 'DOWN WITH THE SHIP', 'MADE THEM CRY', 'NEW MEDIA', 'I LEARNED IT IN BALLET CLASS', 'FRONTWORDS & BACKWORDS', 'SILENT B', 'SCULPTURE MATERIAL', 'CHARACTERS FROM MOVIES', 'ITALIAN LITERATURE', 'TV DRAMA MAMAS', 'U.S. GRANT', "HERE'S LOOKING AT YOU, KID", 'ALL HAT', 'THEATER ALFRESCO', 'ALLITERATION ALLOTMENT', 'GUITAR PLAYER', 'ONE WORD OR TWO', 'THE BOSTON TEA PARTY', 'SECOND-LARGEST U.S. CITIES', 'TOUR OF JUDY', 'BRAZILIAN WORDS & PHRASES', 'ARBOR DAY READING?', 'LITTLE LEAGUE', 'WOEFUL WALL STREET', 'CIVIL SERVANTS', '"C"ULINARY CROSSWORD CLUES', 'MUSIC OF YESTERYEAR', 'BIRTH, ART, DEATH', "CELEBS' ORIGINAL NAMES", 'BIG BANDS', 'TRIVIAL STEW', 'UNDER THE MICROSCOPE', 'THE DOLPHINS', 'THE FRANZ LIST', 'THAT\'S SO "LAME"', 'COLLEGE NEWSPAPERS', 'ELF-HELP', 'A EUROPEAN TOUR', 'FAILURE TO COMMUNICATE', 'THE ROCKETS', 'IN THE "BRIG"', 'ALSO KNOWN AS', 'YOU WROTE IT', 'LITERATURE ON FILM', 'STRINGS', 'YARDSTICK', 'THE SPORTS CHANNEL', "WOMEN'S TUITION", 'YOUNG LOVE IN SONG', 'WE JUST LIVE IN IT', 'THE VICE PREZ SEZ', 'MUSIC HONORS', 'FAMOUS TRIALS', 'BATH & BEYOND', 'STATE OF MIND', '20th CENTURY EUROPE', 'BEN & JENNIFER FILMS', 'LOOSE WHEEL', 'A GEOGRAPHY LESSON', 'NOT TO BE CONFUSED: ACTING EDITION', 'FRANCOPHILE UNDER "M"', '"C"LASSICAL MUSICIANS', 'WHO DOES HE THINK HE IS?', 'COAL RIDGE', 'EATING PLACES', "SPORTS '95", 'MIT', 'REAL PEOPLE IN NOVELS', 'I AM I SAID', 'THE "INCA"s', 'BE AFRAID, BE VERY AFRAID', 'TERMS OF ART', "HOW'S YOUR CONSTITUTION?", 'GIRLY MOVIES', 'FOLDING THE NEWSPAPER--& MAGAZINE', 'STATE YOUR CASE', 'PICTURES AT AN EXHIBITION', 'COMEDY TONIGHT', 'SCREEN SIRENS', 'EPIC CURIOUS', 'MARY: ME', 'SINGLE-NAMED CELEBRITIES', 'THE CHEMICAL WORLD', 'NEW AGE STUFF', 'WARTIME IMAGES', 'FAR EAST MOVEMENT', 'YOUR INITIAL RESPONSE IS CORRECT', 'PUT IT ON PAPER', 'CAPITOL THINKERS', 'WELCOME TO CARLSBAD CAVERNS', "'BOUT 100 YEARS AGO", "IT'S TIME FOR TIME", '1910s CINEMA', 'PORTENT POTABLES', 'MOVIE TITLE PAIRS', '100 YEARS OR OLDER', 'NOT YOUR EVERYDAY WORDS', 'RENAISSANCE ARTISTS', 'ELEMENT ETYMOLOGY', 'THE 2011 TIME 100', 'THE BLUE ANGELS', 'STOOGES', 'OUR TROUBLED PLANET', 'I THINK I\'VE HEARD OF "M"', 'HARRIET', 'LESSER-KNOWN EXPLORERS', 'SPORTS BIRDS', '3 CHARACTERS IN SEARCH OF AN AUTHOR', '"JOHN"s', 'POLITICAL SLOGANS', 'THIS OLD HAUNTED HOUSE', '"TRI" TIPS', 'A BIT OF "MIS" INFORMATION', 'PLAY "BALL"', '6 FEET, UNDER', 'I SAY, HERMIONE', '"FIRST" CHRONICLES', "THAT'S ITALIAN!", 'TYPES OF POEMS', "CAN'T QUITE PLACE YOU", 'THE BIG WHIGS', "WHAT'S WRONG WITH YOU?", 'PLANET OF THE CAPES', 'PRIMA DONNA', '2 Es, THEN ONE E', 'COMMON BLONDES', 'BY THE BOOKS', "THE '76ers", 'WORD"Z"', 'ANATOMICAL QUOTES', 'GEISHA GLOSSARY', 'INDUSTRY LEADERS', 'QUOTES ABOUT SPORTS TEAMS?', "IT'S NOT WHAT IT SEEMS", 'SMALL CAPITALS', 'POETIC PLACES', 'THAT ISLAND IS OURS!', 'KITTY LIT', 'G-FORCE', 'OBSERVATIONS & CELEBRATIONS', 'YOU MAKE ME CRY', 'QUESTION, MARK', "ROCKIN' SUBTITLES", 'TCM WITH ROBERT OSBORNE', 'AND SOMETIMES Y', 'WAR OF THE WORLDS', "WASHINGTON'S NATIONAL CATHEDRAL", 'THE RHINOCEROS', '"R" MAN', 'WHO-SIERS', 'FOREIGN 3-LETTER WORDS', 'THOSE CRAZY GUGGENHEIMS', 'MUSIC BUSINESS', 'JUST MISSED THE TOP OF THE CHARTS', 'WHAT\'S THE "PLAN"?', 'THE LILY', 'ROBOTS & ANDROIDS', 'ANIMAL, VEGETABLE OR MINERAL', 'MAKING THE BAND', 'THE SON ALSO RISES', "WHO PLAYED 'EM ON TV?", 'MY BOLOGNA', 'GRAPHIC NOVELS', '"BOY" MOVIES', "WHAT'S NEW IN ARCHAEOLOGY", 'THEIR GREEK EQUIVALENT', '"R" WORLD', 'I JUST SAW A GHOST!', 'SALUTE THE FLAGS', 'MONTY PYTHON', 'SEW WHAT?', 'YOU SANK MY BATTLESHIP!', 'THE 2005 FORTUNE 500', 'FOREIGN COLLEGE TOWNS', 'ME, A PHARAOH', 'COULD IT BE...SATAN?', 'ENCYCLOPEDIA: BROWN', "HE'S A JAMAICAN, MON", 'HODGEPOURRI', 'ISLAND NATIONS', 'LUCY!', 'ANN-A-GRAMS', 'EMINENT VICTORIANS', 'THE FINAL FRONTIER', 'PRESCRIPTION DRUGS', 'HEY, GOOD LOOKING!', 'BELIEVE', "OTHER ALPHABETS' LETTERS", 'CAKE DECORATING', 'THE STREETS OF SAN FRANCISCO', 'FROM THE JAWS OF VICTORY', 'NEW YORKERS', 'MAKING MONEY', 'MOST EVIL BRITONS', 'ORIGINAL GANGSTERS', "AIN'T WE GOT PUN", "ROAMIN' WITH THE ROMANS", 'MISSING', 'THE TROPHY CASE', '"C